apiVersion: apps/v1
kind: Deployment
metadata:
  name: trello
spec:
  selector:
    matchLabels:
      name: trello
  template:
    metadata:
      labels:
        name: trello
    spec:
      containers:
        - image: martinurp/trello
          name: trello
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP