
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trello
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /
  # cambiar 20.72.99.142 por el IP de tu Ingress 
spec:
  ingressClassName: nginx
  rules:
  - host: trello-dev.20.237.44.35.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: trello
            port:
              number: 80